[package]
name = "test-echo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-std ={version="1",features=["std","attributes"]}
structopt = "0.3"
rlimit = "0.8.3"